#!/bin/sh

if [ $# -eq 0 ] ; then
    SRC_DIR="$HOME/.src/"
else
    SRC_DIR="$1"
fi

for i in $(ls $SRC_DIR); do
    tmp="$SRC_DIR$i"
    echo
    echo "-- UPDATING $tmp --"
    echo

    cd $tmp
    if [ -d ".git" ]; then
        git pull
    elif [ -d ".svn" ]; then
        svn up
    fi
done
